# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://alchoi.com'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Albert Choi
# Description of the Site
description: Words and Code
# URL of Image of the Site - TODO
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: freelancer, writer, books, movies, book reviews, movie reviews, coding, software development, software
# URL for the Image of custom Favicon
favicon-url: /assets/favicon.ico

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/wedge-pond.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
#email: acchoi@gmail.com
facebook_username: albert.choi.583
instagram_username: fi_chince
linkedin_username: albert-choi-202b8923
github_username:  fichince

# Google Analytics
#google-analytics: UA-163806439-1

# Disqus
#disqus-shortname: thedevslot

# Name of the Author
author-name: Albert Choi
# URL for the Image of the Author
author-image: /assets/images/headshot.jpg
# 60 Words About the Author
author-about: I write software, and sometimes prose.

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  sort_reverse: true

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
